### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by aendrew** [samsonjs/strftime#45]
Hi!
I want to use this in a front-end app, which I dependency manage using Bower. You should totally create a bower.json file for this. Or alternately, let me know if you want me to do so and do a PR!

**Comment by samsonjs** [comment]
Done. I don't use bower so please let me know if it works.

**Comment by samsonjs** [comment]
Added! Please let me know if it works since I don't use bower.

**Comment by aendrew** [comment]
Looks good to me! You just need to [register the package with the bower directory](http://bower.io/docs/creating-packages/#register):

`bower register strftime git://github.com/samsonjs/strftime.git`
