### ISSUE TITLE
Add to Bower directory

### ISSUE THREAD

**Issue by aendrew** [samsonjs/strftime#46]
Hi again!

You added the bower.json in #45, but haven't yet submitted it to the directory!

`bower register strftime git://github.com/samsonjs/strftime.git`

As is, I need to do `bower install samsonjs/strftime` which is SO TOTALLY LIKE *NINE* CHARACTERS LONGER! :smile:

**Comment by samsonjs** [comment]
Thanks! I was traveling and forgot about this. Registered. No longer do you have to type "samsonjs/" *like an animal*! http://www.kungfugrippe.com/post/20021002957/like-an-animal

🍻

**Comment by aendrew** [comment]
:smile: :+1: :shipit: Woop! Thanks!
