### ISSUE TITLE
add localizations

### ISSUE THREAD

**Issue by samsonjs** [samsonjs/strftime#54]
We can start collecting these here and maybe find a way to bundle them or at least offer them in the main repo.

zh-CN: michaeljayt@bcb4c12743811d51e568175aa7bff3fd2a77cef3

**Comment by joost** [comment]
nl_NL (Dutch) translations:

    var nl_NL = {
            days: ['zondag', 'maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag'],
            shortDays: ['zon', 'maa', 'din', 'woe', 'don', 'vri', 'zat'],
            months: ['januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december'],
            shortMonths: ['jan', 'feb', 'mar', 'apr', 'mei', 'jun', 'jul', 'aug', 'sep', 'okt', 'nov', 'dec'],
            AM: 'AM',
            PM: 'PM',
            am: 'am',
            pm: 'pm',
            formats: {
                D: '%d/%m/%y',
                F: '%d-%m-%Y',
                R: '%H:%M',
                X: '%T',
                c: '%a %b %d %X %Y',
                r: '%I:%M:%S %p',
                T: '%H:%M:%S',
                v: '%e-%b-%Y',
                x: '%D'
            }
        }

**Comment by joost** [comment]
You should be able to get a lot of translations via something like https://github.com/svenfuchs/rails-i18n.
See the YAML files in https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale

**Comment by Noitidart** [comment]
This is awesome! I support this! I was looking for a repo of a bunch of localizations.

**Comment by samsonjs** [comment]
These have landed in master and will be in version 0.10 which I'll release shortly. I'll accept pull requests to add more bundled locales but for now there are the 9 from @iFixit, and zh_CN from @michaeljayt. Thanks all!
