### ISSUE TITLE
Possible bug with %U

### ISSUE THREAD

**Issue by clexit** [samsonjs/strftime#56]
This looks like a bug with %U:

console.log( strftime('%U', (new Date('03-25-2017 00:00:00'))) )  // 12
console.log( strftime('%U', (new Date('03-26-2017 00:00:00'))) )  // 13
console.log( strftime('%U', (new Date('03-27-2017 00:00:00'))) )  // 12
console.log( strftime('%U', (new Date('04-02-2017 00:00:00'))) )  // 13

**Comment by clexit** [comment]
Should the issue be reopened, since the fix was reverted?

**Comment by samsonjs** [comment]
Yup, reopened.

**Comment by samsonjs** [comment]
Ok, master is fixed and it will be rolled out in 0.9.1 shortly. We had a bug in the tests but it's sorted. Thanks for the report @clexit!

**Comment by clexit** [comment]
Thanks for the quick fix!
