### ISSUE TITLE
Milliseconds returning NaN

### ISSUE THREAD

**Issue by thiagoloddi** [samsonjs/strftime#63]
Hello,

I've been using strftime for some time now and never any problems with it, until I downloaded the latest version recently. It appears it has some kind of bug when displaying milliseconds.
In version 0.8.0 everything worked fine, but in version 0.9.0 it appears that time between milliseconds appears as 00NaN.

Running this script:  

var testDate = function(){
  for(var i = 0; i < 1000; i++){
    var dateTime = strftime("%Y-%m-%d %H:%M:%S:%L")
    console.log(dateTime)
  }
}

On the left is what I got for version 0.9.0 and on the right version 0.8.0
![screen shot 2015-05-29 at 6 57 04 pm](https://cloud.githubusercontent.com/assets/10400276/7893468/9213058e-0634-11e5-81b0-156bfce2104c.png)

Do you have any previsions for this bug to be fixed? Is there anything I can configure in my computer so it works properly?

Thanks!

**Comment by samsonjs** [comment]
It's a reproducible bug introduced in 0.9.0 and I have a fix in the works here. After a bit more testing I'll release a fix for this ASAP as 0.9.1.

Thanks for the report!
