### ISSUE TITLE
%-y does not omit leading zero

### ISSUE THREAD

**Issue by prime300th** [samsonjs/strftime#84]
reproduce code
https://runkit.com/prime300th/61daa3d288a6740008742497
```
console.log(strftime('%-y', new Date('2001-02-03T04:05:06')));
```

expected: 1
actual: 01

**Comment by samsonjs** [comment]
This was just released in [version 0.10.2](https://github.com/samsonjs/strftime/releases/tag/v0.10.2) and is up on npm now.
