### ISSUE TITLE
Test fails for %c

### ISSUE THREAD

**Issue by aryan-debug** [samsonjs/strftime#85]
Specifically, the test fails because of %Z. I set the timezone to America/Vancouver, and the `date.toString` function returns `Pacific Daylight Saving Time`   

```var tzString = date.toString().match(/\(([\w\s]+)\)/);```

but the test asserts `assert.format('%c', 'Tue 07 Jun 2011 11:51:45 AM Pacific Daylight Time', 'Tue 07 Jun 2011 06:51:45 PM GMT');`

I am not sure whether the test needs to be updated or the code. Let me know and I will fix whatever it is.

**Comment by samsonjs** [comment]
Thanks for the report! It looks like this was updated from "Pacific Daylight Time" and it should now be "Pacific Daylight Saving Time".
