### ISSUE TITLE
Using "let" requires ES6 since v0.10.2

### ISSUE THREAD

**Issue by mherold** [samsonjs/strftime#87]
Not sure whether this was intended, but during the fix of #84 you introduced a `let` (which is not available in ES5). This may break  compatibility when doing a patch update from v0.10.1 to v0.10.2 (`Unexpected token: name (year)`).

https://github.com/samsonjs/strftime/blob/v0.10.2/strftime.js#L652

**Comment by samsonjs** [comment]
Thanks for letting me know. I'll release 0.10.3 with a fix shortly, just waiting on one more change to land and then I'll create the release.
