### ISSUE TITLE
Chinese mis-mapping

### ISSUE THREAD

**Issue by mogando668** [samsonjs/strftime#88]
i'm Chinese/English bi-lingual mothertongue (the lovely peculiarity of being from HKG), and I think your Chinese mappings might be slightly off : 
```

  months: ['一月份', '二月份', '三月份', '四月份', '五月份', '六月份', '七月份', '八月份', '九月份', '十月份', '十一月份', '十二月份'],
            shortMonths: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
           
```
Both `months `and `shortMonths `should be using the existing values from `shortMonths`. Having the `份` suffixes  make them adjectives, describing "things happening in July", etc, 

but that's very awkward when used in a calendar context.

**Comment by samsonjs** [comment]
Thanks for your report! Please open a pull-request with your proposed changes and I'll make a new release soon.
